### ISSUE TITLE
Implementation-specific parameters

### ISSUE THREAD

**Issue by giorgiobasile** [resourcesync/py-resourcesync#1]
Hi, I'm trying to integrate my [Elasticsearch plugin](https://github.com/openminted/omtd-rspub-elastic) that I developed for [rspub-core](https://github.com/EHRI/rspub-core).
What I would like to achieve is being able to pass to the ResourceSync constructor a bigger set of parameters containing both the generic ones required by the library + some others related to Elasticsearch (i.e. host, port, index), that should be used by my custom generator in order to properly execute queries and retrieve resources.
```
rs = ResourceSync(
              generator="ElasticResourceListGenerator",
              strategy="resourcelist",
              url_prefix="http://example.com",
              max_items_in_list=1000,
              zero_fill_filename=4,
              is_saving_pretty_xml=True,
              is_saving_sitemaps=True,
              has_wellknown_at_root=True,
              ................
              elastic_host="localhost",
              elastic_port=9200,
              elastic_index="resync-dit-open",
              elastic_resource_doc_type="resource",
              elastic_change_doc_type="change")
```

I made some attempts to extend the Parameters class, but I ended up being forced to extend other classes; for instance, ResourceSync [instantiates a new Parameters object](https://github.com/resourcesync/py-resourcesync/blob/master/resourcesync/resourcesync.py#L128) from a dictionary in its constructor, so it's not possible to actually use an extended version of Parameters.

So I was wondering whether there is a straightforward, "correct" way to provide specific parameters required by a custom generator. Thanks.

**Comment by hariharshankar** [comment]
Hi, 

Thanks for pointing this out. If the ResourceSync constructor accepted an instance of the Parameter class among its argument, would that solve this? The parameter object passed will be an instance of the extended Parameter class that will override any existing default. 

The constructor will only instantiate a new Parameter object when no such object is provided.

For eg:
```python
params = Parameters(
                generator="ElasticSearchListGenerator",
                ...................
                elastic_host="localhost",
                elastic_port=9200)
rs = ResourceSync(parameters=params)
```
I think this will be a clean solution. If this is acceptable for you, I will implement and push this right away.

**Comment by giorgiobasile** [comment]
Yes, that would allow me to create an extended version of `Parameters` to be passed to `ResourceSync`. The only issue is that this new `ElasticParameters` class should have a constructor like this one:
```
class ElasticParameters(Parameters):

    def __init__(self, **kwargs):
        super(ElasticParameters, self).__init__(**kwargs)
        # now I can read the elasticsearch custom parameters
        ....
```
Unfortunately, when I was trying to create a new `ElasticParameters` object, passing a vocabulary with all the required parameters, I was getting a ValueError since `Parameter` wasn't able to ignore my custom elasticsearch keys. Do you think there is another way around this issue?

**Comment by hariharshankar** [comment]
I understand the problem better now. I have updated the Parameters class to accept any new generator specific parameters. You should be able to pass the new parameters to the ResourceSync constructor now (like your first eg) and they will be treated as any other core parameter. Please give it a try and let me know.
