### ISSUE TITLE
URI validation when a port number is specified

### ISSUE THREAD

**Issue by giorgiobasile** [resourcesync/py-resourcesync#12]
The current framework doesn't allow URI prefixes to specify port numbers. This is due to [this](https://github.com/resourcesync/py-resourcesync/blob/master/resourcesync/parameters/parameters.py#L170) sanity check. I noticed this while I was generating documents which were exposed by a local server, but it may well be that a ResourceSync server may be available on a different port than 80.
Is it the case that this constraint needs to be relaxed, given that the [URI specification](https://tools.ietf.org/html/rfc3986#section-3.2.3) explicitly considers the port number as valid part of a URI? It would require to simply change the validation code in: `is_valid_domain = validators.domain(parts.hostname)`

**Comment by hariharshankar** [comment]
You are right, this constraint should be relaxed. And the current checks are very strict and do not even allow domain names like `localhost`. Fixing this.
