### ISSUE TITLE
Package naming problem

### ISSUE THREAD

**Issue by giorgiobasile** [resourcesync/py-resourcesync#2]
When I try to run a simple script using the library, I get this:
```
Traceback (most recent call last):
  File "/Users/giorgio/core/resourcesync/py-resourcesync/resourcesync/resourcesync.py", line 107, in <module>
    from resourcesync.utils.observe import Observable
ModuleNotFoundError: No module named 'resourcesync.utils'; 'resourcesync' is not a package
```
So far I worked it around changing the name of the `resourcesync.py` file, I don't know if I didn't set it up properly or it has actually to be changed.

**Comment by hariharshankar** [comment]
I am not able to reproduce this issue. Could you please give me more information on this?

**Comment by giorgiobasile** [comment]
No need, I had misconfigured my virtualenv, solved.
