### ISSUE TITLE
plugin or attribute

### ISSUE THREAD

**Issue by dans-er** [resourcesync/py-resourcesync#4]
Hi Harish,

Tested your py-resourcesync with a Generator that walks a directory structure. All seems to be working fine.

What I think is a bit awkward - and I myself am to blame for calling things a `plugin` in the [source-framework](https://github.com/resourcesync/source-framework) - is the way one is supposed to hand over an implementation-specific generator to the framework. It has something to do with who you expect your users will be and what their approach is.

If your users are not used to programming but can point the framework to some kind of directory to look for a python module than a plugin is fine. For programmers it is a bit awkward to hand over an implementation that way. If in the future a programmer would install py-resourcesync with pip and create her own Generator it is strange to have to put the newly created Generator in a directory of the python installation to get it to work. One would expect something along
```
myGenerator = MyGenerator("bla", "bla")
# ... set all kinds of configurations on myGenerator
# then call the framework...
rs = ResourceSync( ...)
rs.set_generator(myGenerator)
rs.execute
```
Think that can be implemented easily.

cheers,
henk

**Comment by hariharshankar** [comment]
Hi @dans-er, yes, totally agree. I will implement this.

**Comment by hariharshankar** [comment]
I have implemented this and updated the readme to reflect the changes. 

@giorgiobasile: this commit may affect your existing elasticsearch implementation. Sorry for the breaking change, but I guess this change is for the better.

**Comment by giorgiobasile** [comment]
That's ok, good job
